---
#
# Project:: macOS DevOps Configurator
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Run all the tasks for tweaking OS X and the user preferences

- include: terminal.yml
- include: preferences.yml
