---
#
# Project:: macOS DevOps Configurator
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Configure and tweak Terminal for the current user

- name: Copy Terminal script to tmp
  copy:
    src: files/TermProfile.scpt
    dest: /tmp/TermProfile.scpt
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755

- name: Copy Terminal profile to opt
  become: true
  become_user: root
  copy:
    src: files/DevOps.terminal
    dest: /opt/Devops.terminal
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0755

- name: Load custom Terminal profile to add it
  shell: osascript /tmp/TermProfile.scpt

- name: Ensure custom Terminal profile is the default window
  osx_defaults:
    domain: com.apple.Terminal
    type: string
    state: present
    key: 'Default Window Settings'
    value: 'Devops'

- name: Ensure custom Terminal profile is the default startup window
  osx_defaults:
    domain: com.apple.Terminal
    type: string
    state: present
    key: 'Startup Window Settings'
    value: 'Devops'
