---
#
# Project:: macOS DevOps Configurator
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Deploy my commonly used dot files

- name: Deploy custom user profile
  get_url:
    url: https://raw.githubusercontent.com/ahrenstein/noodling/master/zsh/zshrc
    dest: "~/.zshrc"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644

- name: Make sure /opt exists
  become: true
  become_user: root
  file:
    path: '/opt'
    state: directory
    owner: root
    group: wheel
    mode: 0755

- name: Deploy custom git configuration
  template:
    src: 'gitconfig.j2'
    dest: "~/.gitconfig"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644

- name: Deploy custom csshX settings
  copy:
    src: 'csshrc'
    dest: "~/.csshrc"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644

- name: Deploy custom ansible config
  copy:
    src: 'ansible.cfg'
    dest: "~/.ansible.cfg"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644

- name: Deploy custom vimrc
  copy:
    src: 'vimrc'
    dest: "~/.vimrc"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644

- name: Verify gnupg directory exists
  file:
    path: '~/.gnupg'
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0700

- name: Deploy custom GPG agent config
  copy:
    src: 'gpg-agent.conf'
    dest: "~/.gnupg/gpg-agent.conf"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644

- name: Deploy custom GPG agent initialization
  copy:
    src: 'gpg-agent-info'
    dest: "~/.gpg-agent-info"
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0644
