---
#
# Project:: macOS DevOps Configurator
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# This role will deploy common directories I use in my home directory and throughout the system.

- name: Deploy Code directory
  file:
    path: "~/Code"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0700

- name: Deploy Protected directory
  file:
    path: "~/Protected"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0700

- name: Deploy Scratch directory
  file:
    path: "~/Scratch"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0700

- name: Create Vagrant directory
  file:
    path: "~/Vagrant"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: 0700

- name: Checkout the VagrantBoxes repo from git
  git:
    repo: https://github.com/route1337/VagrantBoxes.git
    dest: "~/Vagrant"
    force: yes
    depth: 1
